<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseMaui>true</UseMaui> <!-- ← Esto habilita SecureStorage y demás Essentials -->
  </PropertyGroup>

  <ItemGroup>
    <!-- Versión exacta que indica el warning MA002 -->
    <PackageReference Include="Microsoft.Maui.Controls" Version="9.0.111" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Manda2.Contracts\Manda2.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Customer\" />
    <Folder Include="Http\" />
  </ItemGroup>

</Project>
